export const SHELL_BLOCK_UI = 'SHELL_BLOCK_UI';
export const SHELL_SET_THEME = 'SHELL_SET_THEME';

export const TRANSLATIONS_SET_FILTERED_RECORDS =
  'TRANSLATIONS_SET_FILTERED_RECORDS';
export const TRANSLATIONS_SET_SOURCE_RECORDS =
  'TRANSLATIONS_SET_SOURCE_RECORDS';
export const TRANSLATIONS_SET_RECORDS_COUNT = 'TRANSLATIONS_SET_RECORDS_COUNT';

export const HOME_SOURCE_PACKS = 'HOME_SOURCE_PACKS';
export const HOME_LOCAL_PACKS = 'HOME_LOCAL_PACKS';
