export const SHELL_BLOCK_UI = 'SHELL_BLOCK_UI';

export const TRANSLATIONS_SET_ALL_RECORDS = 'TRANSLATIONS_SET_ALL_RECORDS';

export const HOME_SOURCE_PACKS = 'HOME_SOURCE_PACKS';
export const HOME_LOCAL_PACKS = 'HOME_LOCAL_PACKS';
